# Generated by Django 5.1.7 on 2025-03-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='stream_link',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
