# Generated by Django 5.1.7 on 2025-03-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_livestream_stream_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiveStream',
        ),
    ]
